//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortProgramm.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Schedule = new HashSet<Schedule>();
        }
    
        public int EmployeeId { get; set; }
        public string EmployeeFIO { get; set; }
        public string Phone { get; set; }
        public byte[] PassportPhoto { get; set; }
        public int PostId { get; set; }
        public string Email { get; set; }
        public int GenderId { get; set; }
        public byte[] Photo { get; set; }
        public int AdressId { get; set; }
    
        public virtual Adress Adress { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Post Post { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedule { get; set; }
    }
}
