//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortProgramm.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int SheduleId { get; set; }
        public int ShipId { get; set; }
        public string DeparturePort { get; set; }
        public string ArrivalPort { get; set; }
        public System.DateTime DepartureTime { get; set; }
        public System.DateTime ArrivalTime { get; set; }
        public int EmployeeId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Ship Ship { get; set; }
    }
}
